

wandb:
  project_name: FlowMSE
  run_name: train-run

train:
  learning_rate: 1e-5
  n_epochs: 10
  save_path: runs/ckpts
  
  data:
    clean_dir: data/dataset/train/clean
    noisy_dir: data/dataset/train/noisy
    sample_rate: 16000
    duration_sec: 6.0
    batch_size: 8
    num_workers: 4

  stft:
    n_fft: 512
    hop_length: 128
    win_length: 512

test:
  data:
    clean_dir: data/dataset/test/clean
    noisy_dir: data/dataset/test/noisy
    sample_rate: 16000
    duration_sec: 6.0
    batch_size: 1
    num_workers: 1

  stft:
    n_fft: 512
    hop_length: 128
    win_length: 512
